"""create_artifacts_table

Revision ID: 831ac06d7d26
Revises: 818152c07b8e
Create Date: 2026-05-31 13:51:19.220840+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '831ac06d7d26'
down_revision: Union[str, None] = '818152c07b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_artifacts_chat_id_chats'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_artifacts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_artifacts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_chat_id'), 'artifacts', ['chat_id'], unique=False)
    op.create_index('ix_artifacts_created_at', 'artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_created_by'), 'artifacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_artifacts_is_active'), 'artifacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_artifacts_type'), 'artifacts', ['type'], unique=False)
    op.create_index(op.f('ix_artifacts_workspace_id'), 'artifacts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_workspace_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_type'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_is_active'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_by'), table_name='artifacts')
    op.drop_index('ix_artifacts_created_at', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_chat_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
